fastlane_version "2.26.0"

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan(
        scheme: "Kanboard iOS",
        device: "iPhone 8"
    )
  end
end

platform :mac do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan(
        scheme: "Kanboard macOS"
    )
  end
end
